In [2]:
import numpy as np
import sys

# 1. Write a function so that the columns of the output matrix are powers of the input vector.
    #The order of the powers is determined by the increasing boolean argument. Specifically, when increasing 
    #is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


In [10]:
def vand(x, inc):
    n = len(x)
    y= np.column_stack([np.array(x)**(n-1-i) for i in range(n)])

    if inc == False:
        print(y)
        return y
    else:
        print(y[:,-1::-1])
        return y[:,-1::-1]
     
    
def check():4
    
    try:
       x = [int(input('Enter the Elements : ')) for i in range(int(input('Number of Elements required : ')))] 
       inc = np.bool(int(input('Increment value(0-False & 1-True :) ')))
       vand(x, inc)    
    except:
        print("Oops!",sys.exc_info()[0],"occured.")


check()


Number of Elements required : 4
Enter the Elements : 1
Enter the Elements : 2
Enter the Elements : 3
Enter the Elements : 4
Increment value(0-False & 1-True :) 0
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


# Problem Statement 2:
#Given a sequence of n values x1, x2, ..., xn and a window= size k>0, the k-th moving average of the given sequence is defined as follows:
#The moving average sequence has n-k+1 elements as shown below.The moving averages with k=4 of a ten-value sequence (n=10) is shown below


In [11]:
n = np.array([int(input('Enter the Elements : ')) for i in range(int(input('Number of Elements required : ')))])
k = int(input("Enter the Window Size : "))
sum_1 = 0

def movingavg():
    for i in range(0,len(n)-k+1):
        sum_1 = sum(n[i:i+k])
        avg = sum_1/k
        print("y",i+1, "=", avg)
        
        
movingavg()      

Number of Elements required : 10
Enter the Elements : 10
Enter the Elements : 20
Enter the Elements : 30
Enter the Elements : 40
Enter the Elements : 50
Enter the Elements : 60
Enter the Elements : 70
Enter the Elements : 80
Enter the Elements : 90
Enter the Elements : 100
Enter the Window Size : 4
y 1 = 25.0
y 2 = 35.0
y 3 = 45.0
y 4 = 55.0
y 5 = 65.0
y 6 = 75.0
y 7 = 85.0
